// Show Address
//------------Washington---------
$("#WA").mouseenter(function(){         
    $('#washington').show();            
});
$("#WA").mouseout(function(){
    $('#washington').hide(); 
});
//-------------Montana-------------
$("#MT").mouseenter(function(){         
    $('#Montana').show();            
});
$("#MT").mouseout(function(){
    $('#Montana').hide(); 
});
//---------North_Dakota--------------
$("#ND").mouseenter(function(){         
    $('#North_Dakota').show();            
});
$("#ND").mouseout(function(){
    $('#North_Dakota').hide(); 
});
//---------Minnesota--------------
$("#MN").mouseenter(function(){         
    $('#Minnesota').show();            
});
$("#MN").mouseout(function(){
    $('#Minnesota').hide(); 
});
//---------Wisconsin--------------
$("#WI").mouseenter(function(){         
    $('#Wisconsin').show();            
});
$("#WI").mouseout(function(){
    $('#Wisconsin').hide(); 
});
//---------Michigan--------------
$("#MI").mouseenter(function(){         
    $('#Michigan').show();            
});
$("#MI").mouseout(function(){
    $('#Michigan').hide(); 
});
//---------Maine--------------
$("#ME").mouseenter(function(){         
    $('#Maine').show();            
});
$("#ME").mouseout(function(){
    $('#Maine').hide(); 
});
//---------New_York--------------
$("#NY").mouseenter(function(){         
    $('#New_York').show();            
});
$("#NY").mouseout(function(){
    $('#New_York').hide(); 
});
//---------Vermont--------------
$("#VT").mouseenter(function(){         
    $('#Vermont').show();            
});
$("#VT").mouseout(function(){
    $('#Vermont').hide(); 
});
//---------New_Hampshire--------------
$("#NH").mouseenter(function(){         
    $('#New_Hampshire').show();            
});
$("#NH").mouseout(function(){
    $('#New_Hampshire').hide(); 
});
//---------Massachusetts--------------
$("#MA").mouseenter(function(){         
    $('#Massachusetts').show();            
});
$("#MA").mouseout(function(){
    $('#Massachusetts').hide(); 
});
//---------Connecticut--------------
$("#CT").mouseenter(function(){         
    $('#Connecticut').show();            
});
$("#CT").mouseout(function(){
    $('#Connecticut').hide(); 
});
//---------Rhode_Island--------------
$("#RI").mouseenter(function(){         
    $('#Rhode_Island').show();            
});
$("#RI").mouseout(function(){
    $('#Rhode_Island').hide(); 
});
//---------New_Jersey--------------
$("#NJ").mouseenter(function(){         
    $('#New_Jersey').show();            
});
$("#NJ").mouseout(function(){
    $('#New_Jersey').hide(); 
});
//---------Pennsylvania--------------
$("#PA").mouseenter(function(){         
    $('#Pennsylvania').show();            
});
$("#PA").mouseout(function(){
    $('#Pennsylvania').hide(); 
});
//---------Delaware--------------
$("#DE").mouseenter(function(){         
    $('#Delaware').show();            
});
$("#DE").mouseout(function(){
    $('#Delaware').hide(); 
});
//---------Maryland--------------
$("#MD").mouseenter(function(){         
    $('#Maryland').show();            
});
$("#MD").mouseout(function(){
    $('#Maryland').hide(); 
});
//---------Virginia--------------
$("#VA").mouseenter(function(){         
    $('#Virginia').show();            
});
$("#VA").mouseout(function(){
    $('#Virginia').hide(); 
});
//---------Distr_of_Col--------------
$("#DC").mouseenter(function(){         
    $('#Distr_of_Col').show();            
});
$("#DC").mouseout(function(){
    $('#Distr_of_Col').hide(); 
});
//---------West_Virginia--------------
$("#WV").mouseenter(function(){         
    $('#West_Virginia').show();            
});
$("#WV").mouseout(function(){
    $('#West_Virginia').hide(); 
});
//---------Ohio--------------
$("#OH").mouseenter(function(){         
    $('#Ohio').show();            
});
$("#OH").mouseout(function(){
    $('#Ohio').hide(); 
});
//---------Indiana--------------
$("#IN").mouseenter(function(){         
    $('#Indiana').show();            
});
$("#IN").mouseout(function(){
    $('#Indiana').hide(); 
});
//---------Kentucky--------------
$("#KY").mouseenter(function(){         
    $('#Kentucky').show();            
});
$("#KY").mouseout(function(){
    $('#Kentucky').hide(); 
});
//---------North_Carolina--------------
$("#NC").mouseenter(function(){         
    $('#North_Carolina').show();            
});
$("#NC").mouseout(function(){
    $('#North_Carolina').hide(); 
});
//---------Tennessee--------------
$("#TN").mouseenter(function(){         
    $('#Tennessee').show();            
});
$("#TN").mouseout(function(){
    $('#Tennessee').hide(); 
});
//---------South_Carolina--------------
$("#SC").mouseenter(function(){         
    $('#South_Carolina').show();            
});
$("#SC").mouseout(function(){
    $('#South_Carolina').hide(); 
});
//---------Georgia--------------
$("#GA").mouseenter(function(){         
    $('#Georgia').show();            
});
$("#GA").mouseout(function(){
    $('#Georgia').hide(); 
});
//---------Florida--------------
$("#FL").mouseenter(function(){         
    $('#Florida').show();            
});
$("#FL").mouseout(function(){
    $('#Florida').hide(); 
});
//---------Alabama--------------
$("#AL").mouseenter(function(){         
    $('#Alabama').show();            
});
$("#AL").mouseout(function(){
    $('#Alabama').hide(); 
});
//---------Illinois--------------
$("#IL").mouseenter(function(){         
    $('#Illinois').show();            
});
$("#IL").mouseout(function(){
    $('#Illinois').hide(); 
});
//---------Louisiana--------------
$("#LA").mouseenter(function(){         
    $('#Louisiana').show();            
});
$("#LA").mouseout(function(){
    $('#Louisiana').hide(); 
});
//---------Mississippi--------------
$("#MS").mouseenter(function(){         
    $('#Mississippi').show();            
});
$("#MS").mouseout(function(){
    $('#Mississippi').hide(); 
});
//---------Arkansas--------------
$("#AR").mouseenter(function(){         
    $('#Arkansas').show();            
});
$("#AR").mouseout(function(){
    $('#Arkansas').hide(); 
});
//---------Iowa--------------
$("#IA").mouseenter(function(){         
    $('#Iowa').show();            
});
$("#IA").mouseout(function(){
    $('#Iowa').hide(); 
});
//---------Missouri--------------
$("#MO").mouseenter(function(){         
    $('#Missouri').show();            
});
$("#MO").mouseout(function(){
    $('#Missouri').hide(); 
});
//---------South_Dakota--------------
$("#SD").mouseenter(function(){         
    $('#South_Dakota').show();            
});
$("#SD").mouseout(function(){
    $('#South_Dakota').hide(); 
});
//---------Nebraska--------------
$("#NE").mouseenter(function(){         
    $('#Nebraska').show();            
});
$("#NE").mouseout(function(){
    $('#Nebraska').hide(); 
});
//---------Kansas--------------
$("#KS").mouseenter(function(){         
    $('#Kansas').show();            
});
$("#KS").mouseout(function(){
    $('#Kansas').hide(); 
});
//---------Oklahoma--------------
$("#OK").mouseenter(function(){         
    $('#Oklahoma').show();            
});
$("#OK").mouseout(function(){
    $('#Oklahoma').hide(); 
});
//---------Texas--------------
$("#TX").mouseenter(function(){         
    $('#Texas').show();            
});
$("#TX").mouseout(function(){
    $('#Texas').hide(); 
});
//---------Wyoming--------------
$("#WY").mouseenter(function(){         
    $('#Wyoming').show();            
});
$("#WY").mouseout(function(){
    $('#Wyoming').hide(); 
});
//---------Colorado--------------
$("#CO").mouseenter(function(){         
    $('#Colorado').show();            
});
$("#CO").mouseout(function(){
    $('#Colorado').hide(); 
});
//---------New_Mexico--------------
$("#NM").mouseenter(function(){         
    $('#New_Mexico').show();            
});
$("#NM").mouseout(function(){
    $('#New_Mexico').hide(); 
});
//---------Idaho--------------
$("#ID").mouseenter(function(){         
    $('#Idaho').show();            
});
$("#ID").mouseout(function(){
    $('#Idaho').hide(); 
});
//---------Utah--------------
$("#UT").mouseenter(function(){         
    $('#Utah').show();            
});
$("#UT").mouseout(function(){
    $('#Utah').hide(); 
});
//---------Arizona--------------
$("#AZ").mouseenter(function(){         
    $('#Arizona').show();            
});
$("#AZ").mouseout(function(){
    $('#Arizona').hide(); 
});
//---------Hawaii--------------
$("#HI").mouseenter(function(){         
    $('#Hawaii').show();            
});
$("#HI").mouseout(function(){
    $('#Hawaii').hide(); 
});
//---------Alaska--------------
$("#AK").mouseenter(function(){         
    $('#Alaska').show();            
});
$("#AK").mouseout(function(){
    $('#Alaska').hide(); 
});
//---------Oregon--------------
$("#OR").mouseenter(function(){         
    $('#Oregon').show();            
});
$("#OR").mouseout(function(){
    $('#Oregon').hide(); 
});
//---------California--------------
$("#CA").mouseenter(function(){         
    $('#California').show();            
});
$("#CA").mouseout(function(){
    $('#California').hide(); 
});

















